MAINT: improve error message when meson isn't found
mesonbuild/meson-python pull request #631
Opened 2024-05-17 10:21 UTC by rgommers

This is a follow-up to gh-495. 

There are several ways that meson may go missing:
- a non-isolated build and meson isn't installed
- meson executable is specified in pyproject.toml and git submodule is containing it is not initialized (reported as resulting in a confusing error in https://github.com/numpy/numpy/issues/26397)
- the  `MESON` environmnent variable is used by the user and is misspelled

The git submodule case was ending with:
```
meson-python: error: Could not find meson version 0.63.3 or newer, found .
```
and after this ends with:
```
meson-python: error: Could not find specified meson: vendored-meson/meson/meson.py
```

If the executable is missing, the build ended with a very long traceback. Changing `FileNotFoundError` to `ConfigError` elides the traceback and clearly reports that the executable wasn't found. Easy to verify with any package with:
```
$ MESON=nonsense python -m build -wnx
* Building wheel...

meson-python: error: meson executable `nonsense` not found

ERROR Backend subproccess exited when trying to invoke build_wheel
```

2024-05-17 11:30 UTC, dnicolodi requested changes
Thanks @rgommers. It looks good, except for some nitpicking about the spelling of the error messages. Curiously I have similar patch queued locally. In that I also check the return code of `meson --version` and raise an error with what was printed on the standard error if the return code is not zero.

2024-05-17 11:30 UTC, dnicolodi commented on mesonpy/__init__.py
> +            raise ConfigError(f"Could not find specified meson: {meson}")
`Could not find the specified meson: "{meson}"` maybe, adding the article and quotes around the path. I think having the quotes helps when there is white space in the filename.

2024-05-17 11:30 UTC, dnicolodi commented on mesonpy/__init__.py
> +        raise ConfigError(f'meson executable `{meson}` not found') from err
We generally use double quotes `"` around literals in the error messages.

2024-05-17 11:42 UTC, rgommers commented
Thanks @dnicolodi. Adopted your suggestions for error messages.

> In that I also check the return code of `meson --version` and raise an error with what was printed on the standard error if the return code is not zero.

If you have that already, do you want to put that on top of this PR (either push a commit or do in a follow-up PR)?

2024-05-17 11:55 UTC, dnicolodi commented
Sure, I will do that later today.

2024-05-19 10:05 UTC, dnicolodi approved these changes

2024-05-19 10:05 UTC, merged