DOC: minor tweak to docs on invoking pypa/build
mesonbuild/meson-python pull request #707
Opened 2024-11-14 11:08 UTC by rgommers

Addresses [a comment on gh-704](https://github.com/mesonbuild/meson-python/issues/704#issuecomment-2466694466), where a user got tripped up by `python -m build` building an sdist first (and that's typically not what you want).

2024-11-19 12:51 UTC, dnicolodi commented
We have several other example `python -m build` invocation in the documentation? Should we change them to `python -m build --wheel` or is this the time to add that "Creating a binary distribution" we have been talking about and have a note there about the pypa/build unexpected behavior?

2024-12-05 11:02 UTC, rgommers commented
I think we should add `--wheel` to all other instances of `python -m build`. The default is useful only for a single CI job or a release of a pure Python package; I can't think of any time I regularly did _not_ add `--wheel` or `-wnx`.

2025-05-02 12:37 UTC, rgommers commented on docs/how-to-guides/config-settings.rst
> +       $ # note: pip >=23.1 also accepts -C instead of --config-settings
hmm, stray tab characters in this file messing things up

2025-05-31 13:25 UTC, rgommers commented
@dnicolodi this is ready, CI failures were unrelated - PTAL, would be nice to merge it.

2025-05-31 13:41 UTC, rgommers commented on docs/how-to-guides/config-settings.rst
> +                  -Ccompile-args="-j6"
Good idea, will make that change. `pip` 23.1 is old enough by now

2025-11-01 17:24 UTC, rgommers commented on docs/tutorials/introduction.rst
> +``--wheel`` to the invocation.
Added a note on uncommitted changes two paragraphs up, where it already talks about Git.

2025-11-01 17:32 UTC, dnicolodi requested changes

2025-11-01 17:32 UTC, dnicolodi commented on docs/tutorials/introduction.rst
> +uncommitted changes are ignored.
This paragraph is very confusing. What is committed only affects what gets into an sdist, but this section is actually about building a wheel. I think this paragraph needs to be removed and the note about uncommitted changes moved below.

2025-11-01 17:39 UTC, rgommers commented on docs/tutorials/introduction.rst
> +uncommitted changes are ignored.
It's about both sdist and wheels. It's part of the "Creating your first release" section, and clearly does talk about both.

2025-11-01 17:40 UTC, rgommers commented on docs/tutorials/introduction.rst
> +uncommitted changes are ignored.
I'm happy to change it to an admonition while we're at it, but I really just want to get this PR in - it was about adding the `--wheel` flag and not related to the commit status of files at all.

2025-11-01 18:56 UTC, dnicolodi commented on docs/tutorials/introduction.rst
> +uncommitted changes are ignored.
This does not make this paragraph worse, so we can merge this PR and fix this part of the documentation later.

2025-11-01 19:06 UTC, dnicolodi commented
I took the liberty of fixing the commit title (this does not touch how pip is invoked, thus I think the commit title was a typo)

2025-11-01 19:11 UTC, merged